### ISSUE TITLE
File encoding changed to UTF-8

### ISSUE THREAD

**Issue by jimbobdog** [endjin/Templify#22]
I have some batchfiles in ANSI encoding, once Templified thought they are converted to UTF-8 encoding and this stops them working from a command prompt (the byte order mark freaks things out)

Cheers,

James (Simmonds, ex CGO)

**Comment by HowardvanRooijen** [comment]
Hello James,

really sorry - not getting notifications from GitHub on this project.

I'll take a look - I've hit this problem in the last month with another tool and have a fix that I can add to templify. Hope all is good with you.

/h

**Comment by seif** [comment]
@HowardvanRooijen any updates on this?

I can't see how to do this, other than storing the encoding with the manifest after detecting it following an approach like http://stackoverflow.com/questions/3404199/how-to-find-out-the-encoding-of-a-file-c-sharp#3404237 and when deploying a package read the encoding from the manifest and save the file with that encoding.

Or was your fix simpler?

**Comment by HowardvanRooijen** [comment]
I thought I fixed that?

Sent from my iPhone

On 28 Jan 2013, at 15:37, "Seif Attar" <notifications@github.com<mailto:notifications@github.com>> wrote:

@HowardvanRooijenhttps://github.com/HowardvanRooijen any updates on this?

I can't see how to do this, other than storing the encoding with the manifest after detecting it following an approach like http://stackoverflow.com/questions/3404199/how-to-find-out-the-encoding-of-a-file-c-sharp#3404237 and when deploying a package read the encoding from the manifest and save the file with that encoding.

Or was your fix simpler?

**Comment by seif** [comment]
Hmm, doesn't look like it, I still get the problem with 0.6.15130.1, maybe you are confusing it with https://github.com/endjin/Templify/issues/15 ?

**Comment by HowardvanRooijen** [comment]
I need to check – I think I may have made this fix on another tool we use internally and I might be able to port it across.

**Comment by ghost** [comment]
Any word on a fix for this?

**Comment by relston** [comment]
Any update on this? Templify is great but this is causing our script files to freak out. Adding a lot of manual labor to fix.

**Comment by HowardvanRooijen** [comment]
I've just pushed up a new version of Templify (0.7.0.25) - which has both a performance fix and a file encoding fix.

Please download and test from here: https://dl.dropboxusercontent.com/u/5892928/Templify/Templify-Installer.exe

**Comment by ghost** [comment]
There is still a issue with this yes it is UTF-8 but you need make sure you are saving it with out BOM headers! its making all my JavaScript and shells scripts error out when I try to run it because its saving it with BOM. JavaScript wont lint and shell scripts wont run...
